# Generated by Django 3.2.5 on 2021-07-26 20:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Resource name', max_length=20, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Resource description', verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modification date')),
                ('arrived_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arriving date')),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Assigning date')),
                ('shift', models.IntegerField(choices=[(1, 'One (1)'), (2, 'Two (2)'), (3, 'Three (3)')], verbose_name='Shift')),
                ('merchandise', models.IntegerField(choices=[(1, 'Conteneur'), (2, 'Bois'), (3, 'Blé'), (4, 'Voiture'), (5, 'Sucre')], verbose_name='Merchandise')),
                ('crane', models.IntegerField(choices=[(1, 'Crane #1'), (3, 'Crane #3'), (4, 'Crane #4'), (5, 'Crane #5'), (6, 'Crane #6'), (7, 'Crane #7'), (8, 'Crane #8'), (9, 'Crane #9'), (10, 'Crane #10')], null=True, verbose_name='Crane')),
                ('tractor', models.IntegerField(choices=[(1, 'Tractor #1'), (3, 'Tractor #3'), (4, 'Tractor #4'), (5, 'Tractor #5'), (6, 'Tractor #6'), (7, 'Tractor #7'), (8, 'Tractor #8'), (9, 'Tractor #9'), (10, 'Tractor #10')], null=True, verbose_name='Tractor')),
                ('elevator', models.IntegerField(choices=[(1, 'Elevator #1'), (3, 'Elevator #3'), (4, 'Elevator #4'), (5, 'Elevator #5'), (6, 'Elevator #6'), (7, 'Elevator #7'), (8, 'Elevator #8'), (9, 'Elevator #9'), (10, 'Elevator #10')], null=True, verbose_name='Elevator')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
            },
        ),
    ]
